language: node_js
node_js: 9
dist: trusty
sudo: required
script: npm run test:travis
addons:
  sauce_connect: true
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: GIL/5CqfpYMgYIWncuxe0dNJDGBtkcosn6HiUii8zV+I5NjUdVQW4uy8CgfMWE9rYy2mbfPpQ2LXEa9qw7RLVThka7OWScoswre1yMhibwUqpPWtYC6NgajGjk9kqOdB0XrTprvcTpuQJW5gAdPWlR2bXGBxrm70eH+kwxyYHeymJCy8UybYtf7/ipz3DV29t8zWx7PscWR/R2U8ltAOcrj39gnenfUBSQs+3SJ/GPPlOPnrRxzaAO2P1tBNHvfST3bCAK8m6hud6LMxagBLCY4I1+6j2FbOZIyy6Mbqzlmlroodbf7nP77FSA0M/hElbJQGGPu0UhJCbHTucEvewPQBkFAMuA3JObixCGqhEhmJMH1/HIJOGXcLnR0n8ts66gNVcPOKEB9xbkrJAULTydfgqpolPJGVqUdUnk2nkWp1INq4TnfcTjJs7Od029PFACsKR3g9aPjJAm71Zqvxx8W9RBHVm8DnqZf4FHdewrneim2oYup0gdJqYyBsT08FLC8FyXYDhHDhLwUy3T9B5F40pG8qUx3vm6u4lsP7ApkLFWpEfC0O0+Nk0hcDhDbWxEEYnkn6fn6L1IyXCBx1E83ypoaFhLiRChoHpCOois/lNX8fkq+0losQTf8gwLfmU4jm6E9vqaTxmaIS/foMpZBC87dHzfvqR6UorMVzgJM=
